futurasac/config/routes.rb
Rails.application.routes.draw do
  get 'system', controller: :systems, action: :system, alias: 'system'

  devise_for :users
  
  
  resources :districts

  get 'reservation', controller: :reservations, action: :reservation, alias: 'reservation'
  get 'service', controller: :services, action: :service, alias: 'service'
  get 'car', controller: :cars, action: :car, alias: 'car'
  get 'home/index'
  root 'home#index'
  

end

futurasac/app/models/concerns/permissions_concern.rb
module PermissionsConcern
    extend ActiveSupport::Concern
    
    def is_passenger?
        self.permission_level >= 1
    end
    
    def is_driver?
        self.permission_level >= 2
    end
    
    def is_user?
        self.permission_level >= 3
    end
    
    def is_admin?
        self.permission_level >= 4
    end
end

futurasac/app/models/district.rb
class District < ActiveRecord::Base
    
end

futurasac/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include PermissionsConcern
end

futurasac/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  
  def authenticate_passenger!
    redirect_to root_path unless user_signed_in? && current_passenger.is_passenger?
    redirect_to root_path unless user_signed_out? && current_passenger.is_passenger?
  end

  def authenticate_driver!
    redirect_to system_path unless user_signed_in? && current_driver.is_driver?
  end
    
  def authenticate_user!
    redirect_to system_path unless user_signed_in? && current_user.is_user?
  end
    
  def authenticate_admin!
    redirect_to system_path unless user_signed_in? && current_admin.is_admin?
  end
  
  layout :plantilla_by_resource

  def plantilla_by_resource
    'plantilla'
  end
  
  before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :lastname, :identitydocument, :birthdate, :email, :password, :password_confirmation)
    end
  end
end

futurasac/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  layout 'plantilla'
  def car
  end
end

futurasac/app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  layout 'plantilla_sistema'
  
  before_action :set_district, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :authenticate_admin!, only: [:destroy]

  # GET /districts
  # GET /districts.json
  def index
    @districts = District.all
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
  end

  # GET /districts/new
  def new
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
  end

  # POST /districts
  # POST /districts.json
  def create
    @district = District.new(district_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'Distrito creado correctamente.' }
        format.json { render :show, status: :created, location: @district }
      else
        format.html { render :new }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /districts/1
  # PATCH/PUT /districts/1.json
  def update
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to @district, notice: 'Distrito actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    @district.destroy
    respond_to do |format|
      format.html { redirect_to districts_url, notice: 'Distrito eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def district_params
      params.require(:district).permit(:description, :status)
    end
end

futurasac/app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'plantilla'
  def index
  end
end

futurasac/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  layout 'plantilla'
  def reservation
  end
end

futurasac/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  layout 'plantilla'
  def service
  end
end

futurasac/app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  layout 'plantilla_sistema'
  def system
  end
end

futurasac/app/helpers/application_helper.rb
module ApplicationHelper
end

futurasac/app/helpers/cars_helper.rb
module CarsHelper
end

futurasac/app/helpers/districts_helper.rb
module DistrictsHelper
end

futurasac/app/helpers/home_helper.rb
module HomeHelper
end

futurasac/app/helpers/reservations_helper.rb
module ReservationsHelper
end

futurasac/app/helpers/services_helper.rb
module ServicesHelper
end

futurasac/app/helpers/systems_helper.rb
module SystemsHelper
end

futurasac/app/views/cars/car.html.erb
<div class="content">
	<div class="container_12">
		<div class="grid_12">
			<h3>Económico</h3>
		</div>
		<div class="clear"></div>
		<div class="gallery">
			<div class="grid_4"><a href="app/assets/images/big1.jpg" class="gal"><%= image_tag("page3_img1.jpg", :alt => "") %></a></div>
			<div class="grid_4"><a href="app/assets/images/big2.jpg" class="gal"><%= image_tag("page3_img2.jpg", :alt => "") %></a></div>
			<div class="grid_4"><a href="app/assets/images/big3.jpg" class="gal"><%= image_tag("page3_img3.jpg", :alt => "") %></a></div>
		</div>
		<div class="grid_12">
			<h3>Normal</h3>
		</div>
		<div class="clear"></div>
		<div class="gallery">
			<div class="grid_4"><a href="app/assets/images/big4.jpg" class="gal"><%= image_tag("page3_img4.jpg", :alt => "") %></a></div>
			<div class="grid_4"><a href="app/assets/images/big5.jpg" class="gal"><%= image_tag("page3_img5.jpg", :alt => "") %></a></div>
			<div class="grid_4"><a href="app/assets/images/big6.jpg" class="gal"><%= image_tag("page3_img6.jpg", :alt => "") %></a></div>
		</div>
		<div class="grid_12">
			<h3>Vip</h3>
		</div>
		<div class="clear"></div>
		<div class="gallery">
			<div class="grid_4"><a href="app/assets/images/big7.jpg" class="gal"><%= image_tag("page3_img7.jpg", :alt => "") %></a></div>
			<div class="grid_4"><a href="app/assets/images/big8.jpg" class="gal"><%= image_tag("page3_img8.jpg", :alt => "") %></a></div>
			<div class="grid_4"><a href="app/assets/images/big9.jpg" class="gal"><%= image_tag("page3_img9.jpg", :alt => "") %></a></div>
		</div>
		<div class="clear"></div>
	</div>
</div>

futurasac/app/views/districts/_form.html.erb
<%= form_for(@district) do |f| %>
  <% if @district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
      <% @district.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Descripción', {:class => "label_sistema"} %>
    <%= f.text_field :description, {:class => "input_text_sistema"} %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'Estado', {:class => "label_sistema"} %>
    <%= f.check_box :status %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit '  Grabar  ', {:class => "input_bottom_sistema"} %>
  </div>
<% end %>

futurasac/app/views/districts/edit.html.erb
<h3 class="h3_sistema">Editar Distrito</h3>

<%= render 'form' %>
<br>
<%= link_to 'Visualizar', @district, {:class => "a_sistema"} %> |
<%= link_to 'Retornar', districts_path, {:class => "a_sistema"} %>

futurasac/app/views/districts/index.html.erb
<p id="notice"><%= notice %></p>
<h3 class="h3_sistema">Listado de Distritos</h3>
<table id="t01" style="width:40%;">
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @districts.each do |district| %>
      <tr>
        <td><%= district.description %></td>
        <td><%= district.status %></td>
        <td><%= link_to 'Visualizar', district %></td>
        <td><%= link_to 'Editar', edit_district_path(district) %></td>
        <td><%= link_to 'Eliminar', district, method: :delete, data: { confirm: 'Esta seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nuevo Distrito', new_district_path, {:class => "a_sistema"} %>

futurasac/app/views/districts/new.html.erb
<h3 class="h3_sistema">Nuevo Distrito</h3>

<%= render 'form' %>
<br />
<%= link_to 'Retornar', districts_path, {:class => "a_sistema"} %>

futurasac/app/views/districts/show.html.erb
<br>
<br>
<p id="notice"><%= notice %></p>

<p class="label_sistema">
  <strong>Descripción:</strong>
  <%= @district.description %>
</p>

<p class="label_sistema">
  <strong>Estado:</strong>
  <%= @district.status %>
</p>

<%= link_to 'Editar', edit_district_path(@district), {:class => "a_sistema"} %> |
<%= link_to 'Retornar', districts_path, {:class => "a_sistema"} %>

futurasac/app/views/home/index.html.erb
<div class="slider_wrapper ">
	<div id="camera_wrap" class="">
		<div data-src="/assets/slide.jpg"></div>
		<div data-src="/assets/slide1.jpg"></div>
		<div data-src="/assets/slide2.jpg"></div>
	</div>
</div>
<div class="container_12">
	<div class="grid_4">
		<div class="banner">
			<div class="maxheight">
				<div class="banner_title">
					<%= image_tag("icon1.png", :alt => "") %>
					<div class="extra_wrapper">Rápido&amp;
						<div class="color1">Seguro</div>
					</div>
				</div>
				Dorem ipsum dolor sit amet, consectetur adipiscinger elit. In mollis erat mattis neque facilisis, sit ameter ultricies erat rutrum. Cras facilisis, nulla vel viver auctor, leo magna sodales felis, quis malesuad
				<a href="#" class="fa fa-share-square"></a>
			</div>
		</div>
	</div>
	<div class="grid_4">
		<div class="banner">
			<div class="maxheight">
				<div class="banner_title">
					<%= image_tag("icon2.png", :alt => "") %>
					<div class="extra_wrapper">Mejores
						<div class="color1">Precios</div>
					</div>
				</div>
				Hem ipsum dolor sit amet, consectetur adipiscinger elit. In mollis erat mattis neque facilisis, sit ameter ultricies erat rutrum. Cras facilisis, nulla vel viver auctor, leo magna sodales felis, quis malesuader
				<a href="#" class="fa fa-share-square"></a>
			</div>
		</div>
	</div>
	<div class="grid_4">
		<div class="banner">
			<div class="maxheight">
				<div class="banner_title">
					<%= image_tag("icon3.png", :alt => "") %>
					<div class="extra_wrapper">Entrega
						<div class="color1">Valijas</div>
					</div>
				</div>
				Kurem ipsum dolor sit amet, consectetur adipiscinger elit. In mollis erat mattis neque facilisis, sit ameter ultricies erat rutrum. Cras facilisis, nulla vel viver auctor, leo magna sodales felis, quis malesuki
				<a href="#" class="fa fa-share-square"></a>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="c_phone">
	<div class="container_12">
		<div class="grid_12">
			<div class="fa fa-phone"></div>+ 1800 559 6580
			<span>RESERVAR AHORA!</span>
		</div>
		<div class="clear"></div>
	</div>
</div>

futurasac/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  	<title>Futura Taxi SAC</title>
	<meta charset="utf-8">
	<meta name = "format-detection" content = "telephone=no" />
	<%= stylesheet_link_tag    'booking', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'camera', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'owl.carousel', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery-migrate-1.2.1', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'script', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'superfish', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.ui.totop', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.equalheights', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.mobilemenu', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.easing.1.3', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'owl.carousel', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'camera', 'data-turbolinks-track' => true %>
	<!--[if (gt IE 9)|!(IE)]><!-->
	<%= javascript_include_tag 'jquery.mobile.customized.min', 'data-turbolinks-track' => true %>
	<!--<![endif]-->
	<%= javascript_include_tag 'booking', 'data-turbolinks-track' => true %>
	<script>
		$(document).ready(function(){
			jQuery('#camera_wrap').camera({
				loader: false,
				pagination: false ,
				minHeight: '444',
				thumbnails: false,
				height: '28.28125%',
				caption: true,
				navigation: true,
				fx: 'mosaic'
			});
			$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
  <%= csrf_meta_tags %>
</head>
<body class="page1" id="top">
    <div class="main">
	    <%= yield %>
    </div>
	
	<script>
		$(function (){
			$('#bookingForm').bookingForm({
				ownerEmail: '#'
			});
		})
		$(function() {
			$('#bookingForm input, #bookingForm textarea').placeholder();
			});
	</script>
</body>
</html>

futurasac/app/views/layouts/plantilla.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Futura Taxi SAC</title>
	<meta charset="utf-8">
	<meta name = "format-detection" content = "telephone=no" />
	<%= stylesheet_link_tag    'booking', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'camera', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'owl.carousel', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery-migrate-1.2.1', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'script', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'superfish', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.ui.totop', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.equalheights', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.mobilemenu', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.easing.1.3', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'owl.carousel', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'camera', 'data-turbolinks-track' => true %>
	<!--[if (gt IE 9)|!(IE)]><!-->
	<%= javascript_include_tag 'jquery.mobile.customized.min', 'data-turbolinks-track' => true %>
	<!--<![endif]-->
	<%= javascript_include_tag 'booking', 'data-turbolinks-track' => true %>
	<script>
		$(document).ready(function(){
			jQuery('#camera_wrap').camera({
				loader: false,
				pagination: false ,
				minHeight: '444',
				thumbnails: false,
				height: '28.28125%',
				caption: true,
				navigation: true,
				fx: 'mosaic'
			});
			$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<%= csrf_meta_tags %>
</head>
<body class="page1" id="top">
    <div class="main">
    	<%= render "partials/navigation" %>
    	
	    <p style="color: #00008B;"><%= notice %></p>
	  	<p style="color: #FF4500;"><%= alert %></p>
	  	
		<%= yield %>
    </div>
	
	<%= render "partials/footer" %>

	<script>
		$(function (){
			$('#bookingForm').bookingForm({
				ownerEmail: '#'
			});
		})
		$(function() {
			$('#bookingForm input, #bookingForm textarea').placeholder();
			});
	</script>
</body>
</html>

futurasac/app/views/layouts/plantilla_sistema.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Futura Taxi SAC</title>
	<meta charset="utf-8">
	<meta name = "format-detection" content = "telephone=no" />
	<%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'style_sistema', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery-migrate-1.2.1', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'script', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'superfish', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.ui.totop', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.equalheights', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.mobilemenu', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.easing.1.3', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'owl.carousel', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'camera', 'data-turbolinks-track' => true %>
	<!--[if (gt IE 9)|!(IE)]><!-->
	<%= javascript_include_tag 'jquery.mobile.customized.min', 'data-turbolinks-track' => true %>
	<!--<![endif]-->
	<%= javascript_include_tag 'booking', 'data-turbolinks-track' => true %>
	<script>
		$(document).ready(function(){
			jQuery('#camera_wrap').camera({
				loader: false,
				pagination: false ,
				minHeight: '444',
				thumbnails: false,
				height: '28.28125%',
				caption: true,
				navigation: true,
				fx: 'mosaic'
			});
			$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<%= csrf_meta_tags %>
</head>
<body class="body_sistema">
    <div class="contenedor_sistema">
		<header class="header_sistema">
			<div>
				<%= image_tag("logo.png", :alt => "") %>
			</div>
		</header>
		<div class="cuerpo_sistema">
			<div class="ladoizquierdo">
				<%= render "partials/navigation_sistema" %>
			</div>
		
	    	<div class="ladoderecho">
	        	<%= yield %>
	    		<p style="color: #FF4500;"><%= notice %></p>
			  	<p style="color: #FF4500;"><%= alert %></p>
	    	</div>
	    </div>
	    
	    <%= render "partials/footer_sistema" %>

	</div>
</body>
</html>

futurasac/app/views/partials/_footer.html.erb
<footer>
	<div class="container_12">
		<div class="grid_12">
			<div class="f_phone"><span>Llamar al:</span> + 1800 559 6580</div>
			<div class="socials">
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-google-plus"></a>
			</div>
			<div class="copy">
				<div class="st1">
				<div class="brand">Futura<span class="color1">T</span>axi </div>
				&copy; 2015	| Derechos Reservados</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</footer>

futurasac/app/views/partials/_footer_sistema.html.erb
<footer class="footer_sistema">
	<div class="container_12">
		<div class="grid_12">
			<div class="copy">
				<div class="st1_sistema">
				<div class="brand">Futura<span class="color1">T</span>axi </div>
				&copy; 2015	| Derechos Reservados</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</footer>

futurasac/app/views/partials/_navigation.html.erb
<header>
	<div class="menu_block ">
		<div class="container_12">
			<div class="grid_12">
				<nav class="horizontal-nav full-width horizontalNav-notprocessed">
					<ul class="sf-menu">
						<li><%= link_to 'Inicio', root_path %></li>
						<li><%= link_to 'Vehículos', car_path %></li>
						<li><%= link_to 'Servicios', service_path %></li>
						<li><%= link_to 'Reservar', reservation_path %></li>
						<% if user_signed_in? %>
							<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
						<% else %>
						    <li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
						    <li><%= link_to 'Crear Cuenta', new_user_registration_path %></li>
						<% end %>
					</ul>
				</nav>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="container_12">
		<div class="grid_12">
			<h1>
				<%= image_tag("logo.png", :alt => "") %>
			</h1>
			<% if user_signed_in? %>
				<div style="float: right; color: #00008B;">Bienvenido <%= current_user.name %></div>
			<% else %>
			    <div></div>
			<% end %>
		</div>
	</div>
	<div class="clear"></div>
</header>

futurasac/app/views/partials/_navigation_sistema.html.erb
<div>
	<nav>
		<ul class="nav_ul">
			<li class="nav_ul_li"><%= link_to 'Clientes', root_path, {:class => "nav_ul_li_a"} %></li>
			<li class="nav_ul_li"><%= link_to 'Servicios', car_path, {:class => "nav_ul_li_a"} %></li>
			<li class="nav_ul_li"><%= link_to 'Tarifas', service_path, {:class => "nav_ul_li_a"} %></li>
			<li class="nav_ul_li"><%= link_to 'Distritos', districts_path, {:class => "nav_ul_li_a"} %></li>
			<li class="nav_ul_li"><%= link_to 'Choferes', reservation_path, {:class => "nav_ul_li_a"} %></li>
			<li class="nav_ul_li"><%= link_to 'Vehiculos', reservation_path, {:class => "nav_ul_li_a"} %></li>
			<% if user_signed_in? %>
			    <li class="nav_ul_li"><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
			<% else %>
			    <li class="nav_ul_li"><%= link_to 'Iniciar Sesión', new_user_session_path, {:class => "nav_ul_li_a"} %></li>
			    <li class="nav_ul_li"><%= link_to 'Crear Cuenta', new_user_registration_path, {:class => "nav_ul_li_a"} %></li>
			<% end %>
		</ul>
	</nav>
	<div class="clear"></div>
</div>

futurasac/app/views/reservations/reservation.html.erb
<div class="content">
	<div class="container_12">
		<div class="grid_5">
			<h3>Formulario de Reserva</h3>
			<form id="bookingForm">
				<div class="fl1">
					<div class="tmInput">
						<input name="Name" placeHolder="Nombre:" type="text" data-constraints='@NotEmpty @Required @AlphaSpecial'>
					</div>
					<div class="tmInput">
						<input name="From" placeHolder="Origen:" type="text" data-constraints="@NotEmpty @Required ">
					</div>
				</div>
				<div class="fl1">
					<div class="tmInput">
						<input name="Email" placeHolder="Email:" type="text" data-constraints="@NotEmpty @Required @Email">
					</div>
					<div class="tmInput mr0">
						<input name="To" placeHolder="Destino:" type="text" data-constraints="@NotEmpty @Required">
					</div>
				</div>
				<div class="clear"></div>
				<strong>Hora</strong>
				<div class="tmInput">
					<input name="Time" placeHolder="" type="text" data-constraints="@NotEmpty @Required">
				</div>
				<div class="clear"></div>
				<strong>Fecha</strong>
				<label class="tmDatepicker">
					<input type="text" name="Date"	placeHolder='27/11/2015' data-constraints="@NotEmpty @Required @Date">
				</label>
				<div class="clear"></div>
				<div class="tmRadio">
					<p>Comodidad</p>
					<input name="Comfort" type="radio" id="tmRadio0" data-constraints='@RadioGroupChecked(name="Comfort", groups=[RadioGroup])' checked/>
					<span>Económico</span>
					<input name="Comfort" type="radio" id="tmRadio1" data-constraints='@RadioGroupChecked(name="Comfort", groups=[RadioGroup])' />
					<span>Normal</span>
					<input name="Comfort" type="radio" id="tmRadio2" data-constraints='@RadioGroupChecked(name="Comfort", groups=[RadioGroup])' />
					<span>Vip</span>
				</div>
				<div class="clear"></div>
				<div class="fl1 fl2">
					<em>Adultos</em>
					<select name="Adults" class="tmSelect auto" data-class="tmSelect tmSelect2" data-constraints="">
						<option>1</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<div class="clear height1"></div>
				</div>
				<div class="fl1 fl2">
					<em>Niños</em>
					<select name="Children" class="tmSelect auto" data-class="tmSelect tmSelect2" data-constraints="">
						<option>0</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
				<div class="clear"></div>
				<div class="tmTextarea">
					<textarea name="Message" placeHolder="Mensaje" data-constraints='@NotEmpty @Required @Length(min=20,max=999999)'></textarea>
				</div>
				<a href="#" class="btn" data-type="submit">Grabar</a>
			</form>
		</div>
		<div class="grid_6 prefix_1">
			<a href="vehiculo.html" class="type"><%= image_tag("page1_img1.jpg", :alt => "") %><span class="type_caption">Económico</span></a>
			<a href="vehiculo.html" class="type"><%= image_tag("page1_img2.jpg", :alt => "") %><span class="type_caption">Normal</span></a>
			<a href="vehiculo.html" class="type"><%= image_tag("page1_img3.jpg", :alt => "") %><span class="type_caption">Vip</span></a>
		</div>
		<div class="clear"></div>
	</div>
</div>